#!/bin/bash

source $HOME/.grokfiles/lib/set_env_variables.sh

cd "$GROK_ROOT"

###############################################################################
# DEFINE LOGGING FUNCTIONS
#

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

###############################################################################
# DEFINE INSTALL FUNCTIONS
#

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "~/$(basename "$src") already exists: [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

#
# Symlinks all `*.symlink` files into $HOME with the same name
#
symlink_dotfiles () {
  info 'symlinking topic dotfiles to home directory'
  echo ''

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find "$GROK_TOPICS" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.symlink}")"
    link_file "$src" "$dst"
  done
}

###############################################################################
# INSTALL
#

echo ''

symlink_dotfiles

# Set shell to zsh
info "setting default shell"
source $GROK_LIB/set_default_shell.sh

# Run topic install.sh scripts.
info "installing dependencies"
source $GROK_LIB/run_topic_installs.zsh

echo ''
echo '  All installed!'
