alias ni='npm install'
alias nid='npm install $1 --save-dev'
alias nis='npm install $1 --save'
alias nu='npm uninstall'
alias nud='npm uninstall $1 --save-dev'
alias nus='npm uninstall $1 --save'
alias ns='npm start --silent'
alias nt='npm test --silent'
alias nl='npm run lint --silent'
alias nb='npm run build --silent'

alias nsw='npm run start:watch --silent'
alias ntw='npm run test:watch --silent'
alias nlw='npm run lint:watch --silent'
alias nlf='npm run lint:fix --silent'
alias nbw='npm run build:watch --silent'
